apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: <your-namespace>  # Specify the namespace
spec:
  type: ClusterIP
  ports:
    - port: 3306 #mysql port
  selector:
    app: mysql
