apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-pv
  namespace: devops
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /mnt/data  # Path on the host machine
