apiVersion: v1
kind: PersistentVolume
metadata:
  name: your-pv-name #change here
  namespace: your-namespace #change here
spec:
  capacity:
    storage: 3Gi #change here according to your needs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /mnt/data  # Path on the host machine
